### ISSUE TITLE
[QUESTION] Example of overriding type behavior with implicits?

### ISSUE THREAD

**Issue by DrewWeth** [andyglow/scala-jsonschema#1]
@andyglow Hi I was wondering if you could give an example of overriding types behavior. For example:

`case class AnyThing(value:Any)`
and when I do `Json.schema[AnyThing].asCirce()` it says 
```
Error: schema for Any is not supported, 
```

I've tried making giving an implicit conversion of Any to a string value but it doesn't seem to work. Should I just try to implicitly convert `AnyThing` into an object with supported types? Im trying to avoid rewriting very complex objects with valid or omitted attributes.

I get the feeling this can be done because of this `Implicit.getOrElse(tpe, genTree)` in `SchemaMacro.scala`. I just can't figure it out or find an example.

Thank you!

**Comment by andyglow** [comment]
Hey, @DrewWeth! Let me ask what json schema you expect to have from `Any`?

**Comment by DrewWeth** [comment]
@andyglow Thanks for responding! Sure thing, I have a primitive example of:

`case class ExampleObject(foo:Map[String, Any])`

It seems like turning any `Any` something else would mess up every object's resolution, but I'd love to turn the field `foo` into `Option[Map[String, String]]` or something.

I tried doing that with implicits, but It seems `SchemaMacro.impl[T]` doesn't take the implicits, example below. 😢 

```
val mapStringAnySchema = Schema.`object`.Field("foo", Schema.string(None, None), false)
implicit val exampleObjectSchema = Schema.`object`[Map[String, Any]](mapStringAnySchema)

implicit val exampleSchema = Json.schema[ExampleObject]
```

**Comment by DrewWeth** [comment]
So I gave up on all that stuff and just created simplified versions of the case class and sub-components I wanted a schema of, with the supported types. Seems like passing in definitions of how to parse custom types into the supported types would be useful.
