### ISSUE TITLE
Add support for readOnly properties

### ISSUE THREAD

**Issue by zacwolfe** [andyglow/scala-jsonschema#104]
It would be great to have support for [readOnly](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.4) properties, both explicitly at the [Field](https://github.com/andyglow/scala-jsonschema/blob/master/core/src/main/scala/json/Schema.scala#L290) level and via annotations as well.

Great work on the library--well organized, easy to use, much needed. Thanks for your hard work.

**Comment by andyglow** [comment]
hey, @zacwolfe 
thanks for the appreciation

as for `readOnly`, yes, it's missed so far. 
Thanks for reminding me, I completely forgot about that.

Will add it in next release.

**Comment by zacwolfe** [comment]
Wonderful, look forward to seeing it!
