### ISSUE TITLE
Case object support for Sum Type definition

### ISSUE THREAD

**Issue by Guillaume-iov42** [andyglow/scala-jsonschema#106]
Hello.
It looks like case objects are not supported when mixed with case classes as leaf values in complex enums?

Example:

```
sealed trait Foo
object Foo {
  final case class Bar(value: String) extends Foo
  final case object Baz extends Foo
}

val foo = json.Json.schema[Foo]
```

Gets me the following error: `Only Scala case classes are supported for Sum Type leafs. Please consider using of them for Sum Types with base 'Foo' or provide a custom implicitly accessible json.Schema for the Sum Type.`

If I have only case classes, or only case objects, it works as expected.
Is there an easy workaround?

**Comment by Guillaume-iov42** [comment]
So as a workaround, I'm using an explicit schema for that, but that kind of defeats the purpose of automatic generation...

```
val schema = oneof(Set(`object`(Field("value", `string`[String]())), enum(Set("Baz", ...))))
```

**Comment by andyglow** [comment]
Historically sealed traits has been treated as
- either `enum` - a set of case objects
- or `oneof` - in case all members are case classes

but I see your point, what you are looking for seems more like a hybrid solution
where all case objects would be collected into one enum and with the rest case classes will be wrapped into `oneof`

**Comment by andyglow** [comment]
@Guillaume-iov42 what json-library are you using btw? which one supports this?

**Comment by vlfig** [comment]
Hi,

```scala
package com.mycom.test

import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import json.Json
import json.Schema._

sealed trait HybridSum
object HybridSum {
  case class V1(id: Int, name: String) extends HybridSum
  case object V2 extends HybridSum
  case object V3 extends HybridSum
}

class TestSchemasSpec extends AnyWordSpec
  with PermissionInstances
  with Matchers {

  "PermissionForAssetType" should {
    "generate schema for hybrid Sealed Trait family" in {
      import `object`.Field

      Json.schema[HybridSum] shouldEqual `oneof`(Set(
        `object`(
          Field("id", `integer`),
          Field("name", `string`)),
        `enum`(Set("V2", "V3"))))
    }
  }
}
```

stil gives `TestSchemasSpec.scala:23:18: Only Scala case classes are supported for Sum Type leafs. Please consider using of them for Sum Types with base 'com.mycom.test.HybridSum' or provide a custom implicitly accessible json.Schema for the Sum Type. [23:18]` with `0.6.1`.
