### ISSUE TITLE
How does one use refined?

### ISSUE THREAD

**Issue by volker48** [andyglow/scala-jsonschema#109]
I'm trying to used Refined, but I'm running into errors.
```scala
import eu.timepit.refined._
import eu.timepit.refined.api.Refined
import eu.timepit.refined.auto._
import eu.timepit.refined.numeric.Positive
import json._
import json.schema.Version.Draft04


object Foo extends App {

  case class Foo(id: Int Refined Positive)

  implicit val fooSchema: json.Schema[Foo] = Json.schema[Foo]

  println(Json.stringify(fooSchema, Draft04()))
}
```

The above results in the following error:

`Error:(13, 57) schema for eu.timepit.refined.api.Refined[Int,eu.timepit.refined.numeric.Positive] is not supported, Foo.Foo
  implicit val fooSchema: json.Schema[Foo] = Json.schema[Foo]`

I've tried writing this a few different ways, but I'm not having any luck getting it to work.

build.sbt:

```scala
name := "foo"

version := "0.1"

scalaVersion := "2.12.12"

libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-json" % "2.9.1",
  "com.github.andyglow" %% "scala-jsonschema" % "0.6.1",
  "com.github.andyglow" %% "scala-jsonschema-play-json" % "0.6.1",
  "com.github.andyglow" %% "scala-jsonschema-refined" % "0.6.1",
)
```

**Comment by volker48** [comment]
Looks like I was missing an import: `import com.github.andyglow.jsonschema.RefinedSupport._`.

**Comment by andyglow** [comment]
yeah.. I know.. sorry for that, this whole thing still lacks a good documentation
