### ISSUE TITLE
Request for new use case

### ISSUE THREAD

**Issue by allenjhan** [andyglow/scala-jsonschema#11]
Hi, thanks for writing this software.

There is one use case that would be really wonderful if it was supported.

Basically, my project uses Circe to serialize an object of type FiniteDuration as a string. So for serialization, 10.seconds is "10s" and 10.milliseconds is "10ms". For deserialization, the deserializer reads the string and decodes it into FiniteDuration.

I would like it if I could generate JSON schema for my case class that contains FiniteDuration. To do that, I need to be able to write a custom json.Schema[FiniteDuration] which acts as json.Schema[String] with validation. Or, just a way to swap json.Schema[FiniteDuration] with json.Schema[String].

So some way to write custom json.Schema class would be nice, or else just a way to swap json.Schema[FiniteDuration] with json.Schema[String]. Currently, the second option doesn't work due to type checking.

**Comment by allenjhan** [comment]
Currently, the workaround I have planned is to create a duplicate case class with all FiniteDuration fields replaced by ValidatedString type alias. ValidatedString is simply String, but by giving it type alias, I can write a validator for the String to use for my schema.

**Comment by andyglow** [comment]
Hi, Allen!
That is a good idea to add scala finite duration support to a standard lib.
For now I would recommend to use common approach, which is to take the `Schema[FiniteDuration]` into the implicit scope while you compile the schema for your model.
That might be done this way:
```
  implicit val scalaFiniteDurationSchema: Schema[FiniteDuration] = `string`[FiniteDuration](None, Some("\d+[ns|ms|days]")) // improve the pattern if you need it of leave it None
```

**Comment by allenjhan** [comment]
Thanks for the quick response! If I can use an implicit val, that would solve all my problems.

I'm getting a compiler error when I try your code though.

I tried it with the code sample you gave, but I'm getting

[error] /Users/allenhan/rep/ice-reactor/core/src/main/scala/vps/reactor/utils/json/JsonSchema.scala:15: object java.lang.String is not a value
[error]   implicit val scalaFiniteDurationSchema: Schema[FiniteDuration] = `String`[FiniteDuration](None, Some("""\d+[ns|us|ms|s|m|h|d]"""))

Using string with a lowercase s, I get

[error] /Users/allenhan/rep/ice-reactor/core/src/main/scala/vps/reactor/utils/json/JsonSchema.scala:15: not found: value string
[error]   implicit val scalaFiniteDurationSchema: Schema[FiniteDuration] = `string`[FiniteDuration](None, Some("""\d+[ns|us|ms|s|m|h|d]"""))

**Comment by allenjhan** [comment]
I took a look at the code itself, and realized it was just a missing import statement. I changed it to Schema.`string` and it worked! I have some other issues that I need to resolve before it compiles though.

**Comment by allenjhan** [comment]
Okay, I got it to work.

Thanks for all your help!
