### ISSUE TITLE
Add support for Maps in which key is a value class or simple wrapper

### ISSUE THREAD

**Issue by Guillaume-iov42** [andyglow/scala-jsonschema#118]
```
case class Key(value: String)
case class MapWrapper(map: Map[Key, String])

val schema = json.Json.schema[MapWrapper]
```

Fails to compile with: `scala.collection.immutable.Map takes 2 type parameters, expected: 1`
Same happens if `Key` is a value class (`extends AnyVal`)

**Comment by andyglow** [comment]
Hey, @Guillaume-iov42 
In case Key is not a value class, what schema do you expect?

**Comment by Guillaume-iov42** [comment]
Same as if it was a value class, I guess...

**Comment by coreywoodfield** [comment]
I agree that this would be great to have for value classes that wrap a `String`. I also agree that it probably doesn't make sense for anything that's not a value class wrapping a `String` (you can't have non-string keys in json)
