### ISSUE TITLE
Add support for custom patternProperties for keys on Schema[Map[String, T]]

### ISSUE THREAD

**Issue by AprilAtProtenus** [andyglow/scala-jsonschema#12]
I would like to restrict the keyspace of `Map[String, _]` keys to help guarantee interoperability with other systems (e.g. NoSQL). However, currently the `"patternProperties"` is fixed with the pattern `"^.*$"`. It would be nice to be able to specify the pattern(s) for keys similarly to how is done with `Schema.string`.

**Comment by andyglow** [comment]
That is a pretty interesting topic. And it doesn't have both simple and beautiful solution at the same time. 
One proper way to go I can see is to analyze map key type and derive `patternProperties` based on a type. Moving this way I would like to examine if we could leverage https://github.com/fthomas/refined. 

The other way is to have type and it's specification loosely coupled. By like providing some specification in macro constructor or something like that. Which i don't really like.

Could you briefly describe what is a real problem you are working on?

**Comment by AprilAtProtenus** [comment]
We have a domain model where for some types there is an `other` field which is a `Map[String, String]`, in case there is information that would be good to store or display but doesn't fit the core data model. We store domain objects in MongoDB, which does not allow certain characters (e.g. `.`) in keys; thus, we restrict the what characters can be used.

**Comment by andyglow** [comment]
all right
could you take a look at this commit https://github.com/andyglow/scala-jsonschema/commit/e8063fdb34ecb62216dad109a93a648ebeea5e9b
is that pretty much what you were looking for?

**Comment by AprilAtProtenus** [comment]
Looks good to me! Thank you so much for adding this so quickly!

**Comment by andyglow** [comment]
let me do the release then

**Comment by AprilAtProtenus** [comment]
fixed by e8063fdb34ecb62216dad109a93a648ebeea5e9b
