### ISSUE TITLE
add support for override annotations

### ISSUE THREAD

**Issue by ygraber** [andyglow/scala-jsonschema#15]
AutoSchema has Ignore, ExposeAs etc. Is anyone working on override annotations? I'm willing to work on in a couple of weeks.

**Comment by andyglow** [comment]
i think that one of the main ideas was to not use annotations for model definition at all, instead everything we need to create a jsonschema should be taken out of type. if that's not enough there is an approach to explicitly specify necessary details during schema compilation (look at how `validations` are defined). by **not** using annotations we can leave model clean and use it to solve different problems like binary-serialization, json-serializaion, json-schema generation, xml-if-you-wish, etc

i think `ignore` might be implemented the way i've explained above, whereas `exposeas` is the functionality which probably might be solved by using `value class` (aka AnyVal) which is supported out of the box now.

what do you think?
