### ISSUE TITLE
CI Build Failure

### ISSUE THREAD

**Issue by gydtaai** [andyglow/scala-jsonschema#157]
CI Build was failed because sbt could not download some packages.
I think it could be a temporary repository problem.

**Comment by gydtaai** [comment]
Hi @andyglow, 
could you please check this?

**Comment by andyglow** [comment]
Hi, @gydtaai 
thanks for binging my attention
fixed that
https://cloud.drone.io/andyglow/scala-jsonschema/115/1/2
