### ISSUE TITLE
import con.github.andyglow.jsonschema.AsPlay._ 

### ISSUE THREAD

**Issue by bjornbak** [andyglow/scala-jsonschema#16]
In the examples in Read.me is mentioned import con.github.andyglow.jsonschema.AsPlay._

First of all there is a typo import **con**.github.

This goes for the other As* examples too

**Comment by andyglow** [comment]
oh. sad mistyping. thanks, for letting me know! 
this definitely should be fixed ))

**Comment by andyglow** [comment]
fixed
