### ISSUE TITLE
Allow partial structure definition

### ISSUE THREAD

**Issue by vlfig** [andyglow/scala-jsonschema#164]
Capturing from #156:

Currently one can either define all the fields or define no fields (`Free`). In some cases, namely wide ADTs, it is helpful to define structures where some fields are specified (required or not) but also other undefined fields are allowed.

It'd be great if we could have
```scala
    `object`(
      Field("something", Json.schema[Int])
    ).withAdditionalProperties(true) // does not exist
```
generate something like
```json
{
  "properties" : {
    "something" : { "type" : "integer" }
  },
  "additionalProperties" : true,
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "required" : [
    "something"
  ]
}
```

Cf. https://json-schema.org/understanding-json-schema/reference/object.html#id2

**Comment by andyglow** [comment]
hello, @vlfig 
if i get it right you don't use derivation, right? i mean you are not looking to map this to scala structs, aren't you?
can you please describe what's your case?

**Comment by andyglow** [comment]
@vlfig please take a look at the pr https://github.com/andyglow/scala-jsonschema/pull/168 would this work for you?

**Comment by vlfig** [comment]
I'm not sure. I can't see a unit test that resembles the use case. If the only thing the `.free` adds is the `additionalProperties` field, then yes. I want to define some (required, in this case) fields _and_ allow others. I presume `0.7.3` would be the one to test with, right?

Yes, we're not using derivation as it currently breaks. It's a fairly wide hierarchy of types.

**Comment by andyglow** [comment]
Hi, @vlfig `0.7.3` is released, if still relevant.
