### ISSUE TITLE
scaladoc of inner class is missing description.

### ISSUE THREAD

**Issue by michellemay** [andyglow/scala-jsonschema#165]
**Describe the bug**

Schema generator does not seems to fully see inner classes scaladoc descriptions. It misses top level description.

**To Reproduce**

Example code:

```
object TestClasses {

  /**
   * Inner class
   * @param x param x
   */
  case class Inner(x: String)

  /**
   * Outer class
   * @param y param y
   * @param inner param inner
   */
  case class Outer(y: String, inner: Inner)
}

class SchemaGeneratorImplicitsTest extends FunSuite {
  import TestClasses._

  test("dummy") {
    implicit val innerSchema = Predef(Json.schema[Inner].toDefinition("Inner"))
    val outerSchema: Schema[Outer] = Json.schema[Outer]
    println(Json.stringify(outerSchema, Draft09("dummy")))
  }
}
```

Will produce this.  Note that top level `description` is missing inside `$defs/Inner` but is correctly grabbing param `x` description.
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "dummy",
  "description": "Outer class",
  "$defs": {
    "Inner": {
      "$anchor": "Inner",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "x": {
          "type": "string",
          "description": "param x"
        }
      },
      "required": [
        "x"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "y": {
      "type": "string",
      "description": "param y"
    },
    "inner": {
      "$ref": "#Inner",
      "description": "param inner"
    }
  },
  "required": [
    "y",
    "inner"
  ]
}
```

**Versions:**
 - jsonschema version 0.7.2
 - scala version 2.12

**Comment by andyglow** [comment]
Hi, @michellemay 
are you sure this is how it should be?
aren't `description` and `title` come at only root level? if no, is it the case for all the drafts, you know?

**Comment by andyglow** [comment]
there is a PR, but help me to figure out please is it really a generic approach, or it may vary from draft to draft

**Comment by michellemay** [comment]
Well, I’m no expert in this but I think that any referenced object should
have it’s description. Probably do not make sense for inlined definitions
though.
