### ISSUE TITLE
Documentation: EnumEntry based enums names overridden do not use the override

### ISSUE THREAD

**Issue by arkangelboss-github** [andyglow/scala-jsonschema#177]
**Describe the bug**
I am using the enumeratum module to generate the schema based on EnumEntry with enums names overridden.

The tests in the code appear to be consistent with my use case (https://github.com/andyglow/scala-jsonschema/blob/master/modules/enumeratum/src/test/scala/com/github/andyglow/jsonschema/EnumeratumSupportSpec.scala).

I was expecting the schema to be generated with the `enum` values from the overridden names, but they show up with the Identifiers.

**To Reproduce**

```
sealed abstract class FancyName(override val entryName: String, val description: String) extends EnumEntry

object FancyName extends Enum[FancyName] with PlayEnum[FancyName] {
  final case object FnOne extends FancyName(entryName = "fn-one", description = "fancy one")
  final case object FnTwo extends FancyName(entryName = "fn-two", description = "fancy two")
  final case object FnCombo extends FancyName(entryName = "fn-one;fn-two", description = "fancy composite")

  override def values: immutable.IndexedSeq[FancyName] = findValues
}

val fancyNameJsonType: json.Schema[FancyName] = Json.schema[FancyName]
println(JsonFormatter.format(AsValue.schema(fancyNameJsonType, Version.Draft04())))
```

generates:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "string",
  "enum": [
    "FnOne",
    "FnTwo",
    "FnCombo"
  ]
}
```

**Expected behavior**

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "string",
  "enum": [
    "fn-one",
    "fn-two",
    "fn-one;fn-two"
  ]
}
```

**Actual results**

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "string",
  "enum": [
    "FnOne",
    "FnTwo",
    "FnCombo"
  ]
}
```

**Versions:**
 - jsonschema version `0.7.2`
 - scala version `2.12.13`

**Additional context**
Also using Play 2.7.9

**Comment by arkangelboss-github** [comment]
I figured out the issue!

I needed to 

`import com.github.andyglow.jsonschema.EnumeratumSupport._`

but it was not clear from the Readme file. 

I could add note in it if it is ok with you @andyglow.

**Comment by andyglow** [comment]
@arkangelboss-github sure, please go ahead. appreciate that

**Comment by andyglow** [comment]
sorted out by #186
