### ISSUE TITLE
presence of an underscore in property names causes failure when using scaladoc annotations

### ISSUE THREAD

**Issue by gordol** [andyglow/scala-jsonschema#188]
When parsing scaladoc, parameters with underscores in the names don't work.

I know it's not standard to do this in Scala (using underscores is frowned upon by convention) but we need to meet contracts that have interfaces with underscored properties in JSON.

This fails:

```scala

/** A dummy object
 *
 * @param foo_bar a parameter example
 */
case class DummyObject(
  foo_bar: List[DsmFileItem]
)

```

with this output:
```
[error] unknown field: foo. DummyObject fields are: foo_bar
[error] Json.schema[DummyObject]
```
i'm inclined to assume the error involves parsing of the scaladoc strings...

because this works just fine:
```scala

/** A dummy object
 *
 */
case class DummyObject(
  @description("a parameter example")
  foo_bar: List[DsmFileItem]
)
```

this generates a schema as expected with `foo_bar` as the field name.

However, I think it's a bug that it doesn't work for scaladoc style docs.

**Comment by andyglow** [comment]
Hi, @gordol 
Thanks for catching it!
Please try `0.7.4`
