### ISSUE TITLE
Validation not compiling for value class

### ISSUE THREAD

**Issue by bjornbak** [andyglow/scala-jsonschema#19]
I have a value class:
```
case class PartnerBucket(val value: String) extends AnyVal with StringField with Validates[PartnerBucket] {
  def isValid: Boolean = !value.isEmpty && PartnerBucket.valueRegExp.findFirstIn(value).isDefined
}
object PartnerBucket {
  val valueRegExp: Regex = "^(s3://|gs://)?[a-z-]+$".r
}
```

And try to define a json-schema withValidation for this: 
```
  implicit val partnerBucketSchema: json.Schema[PartnerBucket] = Json.schema[PartnerBucket]("partnerBucket") withValidation (
    `pattern` := PartnerBucket.valueRegExp.toString()
    )
```

But get this error: `Implicit not found: ValidationBound[com.liveintent.dwh.common.fields.PartnerBucket, String]. Some of validations doesn't match schema type`

If I don't add the implicit schema PartnerBucket works correctly without validation as part of a bigger schema.

How do I declare a ValidationBound? Or how do I implement validations like this?

**Comment by andyglow** [comment]
Hello, Christian! Unfortunately this will not work. There is no support for value classes for validation bound yet. But I agree, it is useful feature, so I added it to the plan for next release.

**Comment by bjornbak** [comment]
When is the next release planed to be?

**Comment by andyglow** [comment]
To be honest I wasn't able to find good and practical solution to support value-classes out of the box in terms of validation. So it may take some time, may be will require entire validation stuff rewriting.

**Comment by andyglow** [comment]
As a workaround for now I am planing to remove `sealed` from `ValidationBound` so people can specify their own like
```
implicit val vb = ValidationBound.mk[UserId, String]
val userIdSchema: json.Schema[UserId] = Json.schema[UserId] withValidation (
  `pattern` := "[a-f\\d]{16}"
)

```

**Comment by andyglow** [comment]
`0.2.2` is on the way

**Comment by bjornbak** [comment]
I think the workaround will work for me.. Will removing sealed be part of 0.2.2

**Comment by andyglow** [comment]
yes
