### ISSUE TITLE
scaladoc descriptions interfere with @discriminator annotations

### ISSUE THREAD

**Issue by mpindado** [andyglow/scala-jsonschema#198]
**Describe the bug**
If you set @discriminator annotations the line before the case class, you lose scaladoc descriptions.

```scala
/** A derived object
 *
 * @param name name
 */
@discriminatorKey("key")
case class Derived(name:String)

```

**Expected behavior**
scaladoc annotations are present in the schema.

**Actual results**
scaladoc annotations are not present in the schema

**Versions:**
 - jsonschema version 0.7.4
 - scala version 2.12

**Additional context**
Workarounds:

```scala

/** A derived object
 *
 * @param name name
 */
@discriminatorKey("key") case class Derived(name:String)


@discriminatorKey("key")
/** A derived object
 *
 * @param name name
 */
case class Derived(name:String)
```

**Comment by andyglow** [comment]
Wow.
Unpleasantly.
This is actually a scaladoc library bug. Let me see what I can find time to fix it.
Thanks for the report!

**Comment by andyglow** [comment]
Hello, @mpindado! please try `0.7.5`.. this issue should be fixed there

**Comment by mpindado** [comment]
Hi @andyglow , I confirm it works with 0.7.6.

Nice job, thank you so much
