### ISSUE TITLE
Default values in Scala case class should be added as default in json-schema

### ISSUE THREAD

**Issue by bjornbak** [andyglow/scala-jsonschema#20]
When I create a json-schema from a case class with default values in Scala like:
```
case class Brilliant(param1: Boolean = true, param2: String = "MyHotString") extends Model
```

The properties in json-schema should have these added as "default" like:
```
    "properties" : {
      "param1" : {
        "type" : "boolean",
        "default": true
      },
      "param2" : {
        "type" : "string",
        "default": "MyHotString"
      },
```

**Comment by andyglow** [comment]
that's a good one. thanks
it comes with json-schema ver 7 spec, right?

**Comment by bjornbak** [comment]
It seems to be part of the spec all the way from draft 4.
comment was added in 7 that is for the schema author only so that is not relevant.

**Comment by andyglow** [comment]
hm. really? how come I could miss it..
all right. either way.. i'll try to find some time next week. will update the thread when it's done

**Comment by andyglow** [comment]
https://github.com/andyglow/scala-jsonschema/pull/21
this is what i have at the moment
will need update documentation, though
do you think this is what you were looking for?

**Comment by bjornbak** [comment]
When do you plan to include this in a release?

**Comment by andyglow** [comment]
`0.2.2` has just been published
