### ISSUE TITLE
Support for building schemas out of data

### ISSUE THREAD

**Issue by sergiojoker11** [andyglow/scala-jsonschema#24]
With this library, one can generate a schema out of a case class, for instance, but it is not possible to generate a schema "on the fly" out of data.

**Comment by andyglow** [comment]
what do you mean by saying `on the fly`?
it is true that it is built to provide convenient way to generate schemas out of case classes, but it not limited to. you can provide schemas for your own types. check tests or joda-time support module.

**Comment by sergiojoker11** [comment]
By `on the fly` I mean building a schema out of data at runtime.
There is a Java library, which I am using right now, that contains a SchemaBuilder that allows you to do so but it is not fully Draft07 compliant. e.g this is the schema object builder. https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/ObjectSchema.java

**Comment by andyglow** [comment]
please take a look at `https://github.com/andyglow/scala-jsonschema/blob/master/api/src/test/scala/com/github/andyglow/jsonschema/AsDraft07Spec.scala`
and at other tests. There you can find some ideas on how to create schemas in runtime.

```
import json.Schema._
import json.schema.Version._
import `object`.Field

`object`(
        Field("foo", `string`[String](None, None)),
        Field("bar", `integer`, required = false),
        Field("baz", `ref`[Boolean]("scala.Boolean", `boolean`("my-bool"))))
```

**Comment by sergiojoker11** [comment]
Does this provide guidance to speed up the generation of valid JsonSchemas of a particular version or stop you somehow from generating invalid Jsonschemas?

**Comment by andyglow** [comment]
this is not generic json. it's a schema constructor
it does the validation at the level available at type level, but if you want you can screw it up in number of ways. there is nothing that can stop you from defining 2 fields with same name for example.

may i ask why do you need that level, why case class abstraction doesn't work for you?

**Comment by sergiojoker11** [comment]
you are saying that if you are defining a schema of type number the class has only defined the fields that you can set and, therefore, you get help from the compiler when developing. Is this correct?

**Comment by andyglow** [comment]
pretty much
the idea is to provide the tool, that would understand semantic of the language and be ready to support constructs such as case class and ADT (sealed trait hierarchy) as long as value classes. it should also go with out of the box support for primitives such as numbers, strings, boolean, etc.. and commonly used structures such as `Option`.

the way it's gonna work is
when compiler needs a json-schema for specified type, it should look up for implicit definition of it and if not found - generate one if possible, otherwise - throw
