### ISSUE TITLE
Will the latest draft be supported on this library?

### ISSUE THREAD

**Issue by audax-shreyaspurohit** [andyglow/scala-jsonschema#28]
https://json-schema.org/draft/2019-09/release-notes.html

**Comment by andyglow** [comment]
Sure. There is a plan for the support. 
As far as i understand it is still not completely defined, right?
I mean, they are saying `NOTE: This page is still being written, and is currently a fairly minimal listing of changes.`

Are there any validation tools which already has leveraged that?

**Comment by audax-shreyaspurohit** [comment]
Thanks for supporting next versions. This library is very useful.

When I look at this page https://json-schema.org/specification.html, it says -
```
The latest Internet-Drafts at the IETF are the draft-handrews-json-schema*-02 documents, which correspond to the 2019-09 meta-schemas. These were published on 2019-09-16.

For a full explanation of both the IETF and meta-schema numbering schemes, how they correspond, and why we are now using the date-based 2019-09 rather than draft-08, see the Specification Links page.
```

When I look at https://tools.ietf.org/html/draft-handrews-json-schema-02, I cant find that note either. 

I must be obviously missing something as I cant find that note.

**Comment by ngbinh** [comment]
version 2019-09 has been published https://json-schema.org/specification.html

**Comment by andyglow** [comment]
hey guys, support of the latest versions is definitely something that I'd like to have implemented
Identification of what has changed and what needs to be done in order lib to be considered NEW version compliant was always challenging though

do you guys know what features needs to be added, what keywords renamed and so on?

i've read through https://json-schema.org/draft/2019-09/release-notes.html
and what i get is that at our end we have to 
- rename `definitions` to `$defs`
- check if we need to use `$anchor` and if se use `$id` verify if we use it right according to new spec.
this must be pretty much it, right?

what do i miss?
