### ISSUE TITLE
Support for json schema draft 2020-12

### ISSUE THREAD

**Issue by jwgcooke** [andyglow/scala-jsonschema#283]
Do you have any plans to support the most recent version of JSON Schema (2020-12)?  Base don what I see in the code and the docs there is currently only support for up to draft 09.

**Comment by andyglow** [comment]
yeah, that would be good to add 2020-12 support
I'm not sure about the timeline thought
if you are willing to contribute, please do
any contribution is appreciated

**Comment by jwgcooke** [comment]
I am (at best) an entry level on the Scala front, I cloned the repo to start seeing if I could handle anything and ran into #284 ... I am happy to poke at it and see what I can do to help.

**Comment by andyglow** [comment]
great. thank you

**Comment by jwgcooke** [comment]
Changes from 09 --> 2020-12

https://json-schema.org/draft/2020-12/release-notes.html
