### ISSUE TITLE
Creating Schema for custom types

### ISSUE THREAD

**Issue by audax-shreyaspurohit** [andyglow/scala-jsonschema#29]
Hello,

Any idea how do I define a schema when using cats [NonEmptyList](https://typelevel.org/cats/datatypes/nel.html).
```
import cats.data.NonEmptyList
case class Error(errorCode: String, desc: String)
object Error {
  implicit val schema: json.Schema[Error] = json.Json.schema[Error]
}

case class Data(errors: Option[NonEmptyList[Error]])

object Data {
  implicit val schema: json.Schema[Data] = json.Json.schema[Data]
}
```

I currently get this error-
```
schema for A is not supported, cats.data.NonEmptyList[Error]
```

Looking at ```SchemaMacro.resolve```, I see the types defined. There is ```Iterable``` and ```Array```. But, I am not able to figure out a way to create a schema where I want to treat ```NonEmptyList``` as an ```Iterable``` because its not really implementing ```Iterable```.

Thanks for any help.

**Comment by andyglow** [comment]
Hey. Cats support has been added since `0.2.5` version as well as support for generic types. Please check it out.

**Comment by audax-shreyaspurohit** [comment]
Thank you! will do
