### ISSUE TITLE
Supporting multi level sealed traits

### ISSUE THREAD

**Issue by holbech** [andyglow/scala-jsonschema#30]
I've found that the macro works for sealed traits, but if they are layered it fails:

    sealed trait Animal {}
    sealed trait Mammal extends Animal {}
    val s = Json.schema[List[Animal]]

I looked into the code, but couldn't grasp how sealed traits are handled, so I cannot offer a PR for fixing this.

**Comment by plokhotnyuk** [comment]
Yeap, the `knownDirectSubclasses` could be applied recursively to gather nested traits (or abstract classes), like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/3612fddf19a8ce23ac973d71e85ef02f79c06fff/jsoniter-scala-macros/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L351-L365). 

The key point is that non-sealed abstractions should be opted out by default to avoid gathering unwanted broad hierarchies from the classpath.

**Comment by andyglow** [comment]
> Yeap, the `knownDirectSubclasses` could be applied recursively to gather nested traits (or abstract classes), like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/3612fddf19a8ce23ac973d71e85ef02f79c06fff/jsoniter-scala-macros/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L351-L365).
> 
> The key point is that non-sealed abstractions should be opted out by default to avoid gathering unwanted broad hierarchies from the classpath.

hey @plokhotnyuk 
pretty cool lookup
i'd borrow it if you don't mind

**Comment by andyglow** [comment]
@holbech nice finding. let me try to fix it. thanks to @plokhotnyuk for recipe!

**Comment by andyglow** [comment]
should be fixed in `0.2.3`. please check
