### ISSUE TITLE
Question: Get Json schema from case class

### ISSUE THREAD

**Issue by agamjainhpe** [andyglow/scala-jsonschema#350]
Hi,

I have a use case in which I want to create a json-schema for  case classes 
I tried running the below code
`val personSchema: json.Schema[Person] = Json.schema[Person]`

the output it's giving is `object(name: string: ReadWrite /R, age: integer: ReadWrite /R, address: string: ReadWrite /R,)`

How do i get string something like mentioned in the Readme?

**Comment by agamjainhpe** [comment]
@andyglow

**Comment by andyglow** [comment]
hello, @agamjainhpe 
right. what you get from `Json.schema` macro is an instance of `Schema[T]`
you can use it as is, it has all the info you needed, but is not so much helpful if you need a json representation of the schema.
for that there is an abstraction called `As*` as well as `Version`
`As*` is a bridge between the `schema` and it's representation in the json world that your app support. Basically there is a bunch of adapters for different json libraries: Circe, Play, Spray, etc..

So, please check tests for the details.

There is also `AsValue` that allows schema representation in internal json language.
Which lets you do something like this:
```
println(JsonFormatter.format(AsValue.schema(schema)))`
```
