### ISSUE TITLE
schema for Char is not supported

### ISSUE THREAD

**Issue by bjornbak** [andyglow/scala-jsonschema#41]
I try to upgrade from 0.2.2 to test #18 but my code doesn't compile with version 0.2.3+

I get the error `schema for Char is not supported`

I use it in a `case class MyCaseClass(val value: Char) extends AnyVal` but even if I do `val mySchema: Schema[Char] = Json.schema[Char]` I get the same error.

I use the following dependencies and have tried version 0.2.3 to 0.2.7-M1
```
		libraryDependencies += "com.github.andyglow" %% "scala-jsonschema-core" % "0.2.7-M1",
		libraryDependencies += "com.github.andyglow" %% "scala-jsonschema" % "0.2.7-M1",
		libraryDependencies += ("com.github.andyglow" %% "scala-jsonschema-circe-json" % "0.2.7-M1")
```

Trying other primitives than Char works eg Byte and Int.

According to the documentation Char is supported out of the box. Is this a bug or removed feature?

**Comment by andyglow** [comment]
Yeah, must be a bug. Let me see

**Comment by andyglow** [comment]
Hey, Christian! 
There is a `0.2.7-M2` with this issue fixed. Do you want to try it out?

**Comment by bjornbak** [comment]
I will - as soon as 0.2.7-M2 hits a maven repo near me :)

**Comment by bjornbak** [comment]
This works. Please release as 0.2.8

**Comment by bjornbak** [comment]
Hi @andyglow,
Is it possible to release this as 0.2.8?
My colleagues using Windows experience strange compile issues after I introduced 0.2.7-M2 to our dependencies.
I would like to rule out -M2 is the reason.

**Comment by holstein-rathlou** [comment]
^--  Just for info, the strange compile issue gives the following error message:
```
[error] C:\Users\chris\IdeaProjects\dwh\dwh-input\src\main\scala\com\liveintent\dwh\common\fields\PartnerBucket.scala:40:77: exception during macro expansion:
[error] java.lang.StringIndexOutOfBoundsException: String index out of range: -49
[error]         at java.lang.String.<init>(String.java:196)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.isSelfRef(SchemaMacro.scala:392)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.lookupSchema$1(SchemaMacro.scala:424)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.getOrElse(SchemaMacro.scala:429)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$.com$github$andyglow$jsonschema$SchemaMacro$$resolve$1(SchemaMacro.scala:455)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$.impl(SchemaMacro.scala:458)
[error]   implicit val partnerBucketSchema: json.Schema[PartnerBucket] = Json.schema[PartnerBucket]("partnerBucket") withValidation (

```

**Comment by holstein-rathlou** [comment]
Hi @andyglow ,
   We seemed to have pinpointed the issue to the (in)famous line separator differences between Linux and Windows. Using Windows format (CRLF - \n\r) leads to failure, while using Linux format (LF - \n) does not. Hopefully, that information will allow you to fix the code at a point in time.
