### ISSUE TITLE
SchemaMacro doesn't work on Windows with CRLF 

### ISSUE THREAD

**Issue by holstein-rathlou** [andyglow/scala-jsonschema#51]
We recently updated to scala-jsonschema v. 0.2.7-M2 using the following libraries: (scala-jsonschema, scala-jsonschema-core, scala-jsonschema-macros, scala-jsonschema-circe-json). With this update, Windows users with CRLF set as line separator in IntelliJ (and otherwise in code) experienced the following error:

`[error] C:\Users\chris\IdeaProjects\dwh\dwh-input\src\main\scala\com\liveintent\dwh\common\fields\PartnerBucket.scala:40:77: exception during macro expansion:
[error] java.lang.StringIndexOutOfBoundsException: String index out of range: -49
[error]         at java.lang.String.<init>(String.java:196)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.isSelfRef(SchemaMacro.scala:392)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.lookupSchema$1(SchemaMacro.scala:424)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$Implicit$2$.getOrElse(SchemaMacro.scala:429)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$.com$github$andyglow$jsonschema$SchemaMacro$$resolve$1(SchemaMacro.scala:455)
[error]         at com.github.andyglow.jsonschema.SchemaMacro$.impl(SchemaMacro.scala:458)
[error]   implicit val partnerBucketSchema: json.Schema[PartnerBucket] = Json.schema[PartnerBucket]("partnerBucket") withValidation (`

This is solved by switching to LF in the code/IntelliJ, but is an unfortunate side effect of the M2 hotfix.

**Comment by andyglow** [comment]
Hi, @holstein-rathlou 
Thanks for reporting it and sorry for the delay
It's fixed in `0.2.8`
