### ISSUE TITLE
support of self-referenced case classes

### ISSUE THREAD

**Issue by ngbinh** [andyglow/scala-jsonschema#55]
I have an use-case that may be beneficial from this feature. I am wondering what's the plan here? I am willing to help but not familiar with the code base.

**Comment by andyglow** [comment]
can you bring some more details onto the plate?
say.. a model itself and the json-lib you use to handle that

**Comment by ngbinh** [comment]
I would like to be able to define a recursive structure such as nested document paragraph or table

**Comment by andyglow** [comment]
i see
may i still ask you to show me, what class hierarchy (simplified version maybe) do you have, and mode importantly, what json-schema do you expect to be generated out of it..

coz, it's not a big problem to handle `recursive types` in scala, but i am not sure how to express this in jsonschema. we can refer fragments from root definition of from fragment definition, but we can't refer root itself.. right?

**Comment by ngbinh** [comment]
Sorry for the late reply. I guess what I need is a form to define recursive structure similar to what mentioned [here](https://stackoverflow.com/questions/35250621/recursive-self-referencing-json-schema/35260879)

```
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "tree": { "$ref": "#/definitions/tree" }
  },
  "definitions": {
    "tree": {
      "type": "object",
      "properties": {
        "value": { "type": "string" },
        "branches": {
          "type": "array",
          "items": { "$ref": "#/definitions/tree" },
          "minItems": 1
        }
      },
      "required": ["value"]
    }
  }
}
```

**Comment by andyglow** [comment]
it seems we can do something like this
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "foo": {
          "$ref": "#/definitions/foo"
        }
      },
      "required": [ "name" ]
    }
  },

"allOf": [ { "$ref": "#/definitions/foo" } ]
}
```

so the schema definition is fully defined in `definitions`, but  this `"allOf": [ { "$ref": "#/definitions/foo" } ]` makes root schema to be taken from definitions
