### ISSUE TITLE
Feature Request: support Map[EnumEntry, V] of enumeratum's EnumEntry

### ISSUE THREAD

**Issue by rolman243** [andyglow/scala-jsonschema#59]
Hi @andyglow,

currently only Map[String, T] is supported, would it be possible to support Map[EnumEntry, V]?

We use [enumeratum library](https://github.com/lloydmeta/enumeratum) to build an enum type.
This type is used as key in a Map. When trying to build a json schema out of this it fails with:

`scala.collection.immutable.Map takes 2 type parameters, expected: 1`

Mapping EnumEntry to String for json should be easy I think, because every EnumEntry defines `def entryName: String`

**Comment by andyglow** [comment]
please find this feature enabled in `0.3.0`

**Comment by rolman243** [comment]
@andyglow Thank you man, it works, really great stuff

**Comment by andyglow** [comment]
Perfect!
Btw what json lib do you use? Circe, etc?

**Comment by rolman243** [comment]
We are using circe and make a lot of use of refined types and enumeratum enums.
I like the minimal amount of boilerplate needed when using these libs and yours fits in perfectly.
Btw I tried to implement the EnumEntry feature by myself, maybe I can contribute the next time, when we are missing something. My only problem is I don't have much experience with macros in scala
