### ISSUE TITLE
Schema derivation fails for optional complex types with a default in 3.0

### ISSUE THREAD

**Issue by dave-handy** [andyglow/scala-jsonschema#66]
I have the following ammonite script:
```
import $ivy.`com.github.andyglow:scala-jsonschema-play-json_2.13:0.3.0`
import json._
case class Bar(b: Int)
implicit val barSchema = Json.schema[Bar]
case class Foo(bar: Option[Bar])
Json.schema[Foo] // succeeds
case class Foo(bar: Option[Bar] = Some(Bar(1)))
Json.schema[Foo] // fails
```
It prints out:

> cmd7.sc:1: Can't infer a json value for bar
>val res7 = Json.schema[Foo] // fails
>                      ^
>Compilation Failed

Moreover if you adjust the imported version to "0.2.1" it succeeds.

I think I've tracked this to changes in the code that prints "can't infer a json value" but I'm not understanding the complexities there quite enough to try to figure out a workaround. It seems like a regression bug to me.

**Comment by dave-handy** [comment]
Testing all the other 0.2.x versions, 0.2.1 is the last where this code succeeds.

**Comment by andyglow** [comment]
hi, @dave-handy 
thanks for reporting it
looks strange, agree
i'll look into this

**Comment by andyglow** [comment]
hey, @dave-handy 
so i've checked the example you attached, to make it work you need to add several details
please take a look at this snippet https://scastie.scala-lang.org/Y04mKBcTR4mpl9LpgFKptA

actually the thing is that jsonschema library doesn't deal with jsons - only with jsonschemas
so library doesn't know how to convert Bar into json
but to make it work it heavily relies on concrete json-lib implementation (play, spray, ujson, etc)
so in your case you need to add an implicit `Writes` for `Bar` into scope and import bridge (for play it is `import com.github.andyglow.jsonschema.AsPlay._`). 
Your example will immediately start working after these steps taken

**Comment by dave-handy** [comment]
Ahh now I understand what "toV" and that error message "can't infer a json value" mean. I will try to apply this to my project and perhaps make a PR for a slightly better error message if you are interested. Thanks!

**Comment by Guillaume-iov42** [comment]
Thank you for your reply, I had exactly the same issue. Maybe that should be in the main README?

**Comment by andyglow** [comment]
Hello, guys. 
This should be in read me certainly. I am planning to rollout a new documentation soon. Will cover this issue there as well.
