### ISSUE TITLE
Scaladoc support is fragile

### ISSUE THREAD

**Issue by gordol** [andyglow/scala-jsonschema#68]
For example, place a quote in your scaladoc:

```scala
/** This is an example to show some "broken" things.
 * 
 * @param foo "Quotes" break JSON schema output
 * @param bar Regex backslash break JSON schema output
 */
case class Foobar( foo: String,   bar: String Refined MatchesRegex[W.`"""\\d{3}[- ]\\d{3}[- ]\\d{4}"""`.T])
```
You'll end up with invalid JSON in your schema output that cannot be parsed because `"` should have been escaped in the schema JSON output.

The same is true for using regexes with escapes.

For example, the `\d` must be escaped to feed the string to the regex parser, but using `\\d` for a digit match will lead to `\d` being outputted into your JSON schema, which is not valid; the json schema needs the `\d` to be escaped as well, like `\\d`.

It seems like the simple solution would be to pass the generated JSON descriptions through an escape function before flushing them to the schema output.

**Comment by andyglow** [comment]
yeah, nice catch
thanks for the report
will cover it in upcoming release

**Comment by andyglow** [comment]
hey, @gordol 
may I ask, btw, how do you create a resulting json string?
Is it `JsonFormatter` or some of supported json-libs?

**Comment by gordol** [comment]
@andyglow 

Indeed, using JsonFormatter 👍

Something like this...

```scala
class JSONGenerator{
  val schemas: Array[(json.Schema[AnyRef], String)] = Array()

  def run = {
    println("\n---------\nGenerating JSON Schemas:")
    for ((schema, name) <- schemas){
      println(name)

      var path = FilenameUtils.getPath(name)
      var dirHandle = new File("gen/json/"+path)
      if(!dirHandle.exists() && dirHandle.mkdirs()){
        println("\n-------\nCreated directories")
      }

      if(dirHandle.exists()){
        var pw = new PrintWriter(new File("gen/json/"+name+".json"))
        pw.write(JsonFormatter.format(AsValue.schema(schema, json.schema.Version.Draft07("/models/"+name))))
        pw.close
      }
    }
  }
}
```

Just extend JSONGenerator, override the schemas array with a reference to the class, and a string representing the directory/file structure where the output schemas will be saved.

```scala
object SomeJSON extends JSONGenerator{
  override val schemas = Array(
    (Json.schema[Foobar], "test/foobar"),
  )
}

object MainGenerator extends App{
  SomeJSON.run
}
```

**Comment by gordol** [comment]
Also I just noticed a typo in my original post above, "backtick" should have been "backslash", apologies. I updated it.

> `@param bar Regex backslash break JSON schema output`

**Comment by andyglow** [comment]
Then this must be fixed with 0.4.0. Please check it

**Comment by gordol** [comment]
Cool I'll review and try it soon this week! 👍

**Comment by gordol** [comment]
Looks good!

**Comment by andyglow** [comment]
cool. nice catch and thanks for the report!
