### ISSUE TITLE
Support for untyped or "metadata" field  

### ISSUE THREAD

**Issue by gavares** [andyglow/scala-jsonschema#71]
I have a case class which is defined similar to the following:
```
case class Payload(id: String, name: String, metadata: JsObject)
```
where JsObject refers to the play-json class. 

The field isn't have to be a JsObject necessarily  but really is just intended to provide a place where a user can specify  arbitrary untyped json.

I tried changing this to Object and tried to imagine how I could represent this as a Map[String, T] of some sort but wasn't able to come up with anything.

I read through docs and wandered through the codebase looking for some indication of how I might achieve this. Is this doable today?

**Comment by andyglow** [comment]
hi, Grant
lets start from, how do you want your metadata object to be described in json-schema terms?
can you give me an example?

**Comment by andyglow** [comment]
something like this?
```
{
  "type": "object",
  "additionalProperties": true
}
```

**Comment by gavares** [comment]
I want to create a field in my schema named "metadata" that has a type of "object".  I need the scala type of that field to be `play.api.libs.json.JsObject` because that allows me to create a play-json `Format` which will understand how to parse the field properly.

So:
```scala
case class Payload(id: String, name: String, metadata: JsObject)
implicit val payloadFmt = Json.format[Payload]
val personSchema: json.Schema[Person] = Json.schema[Person]
```

should compile and
```scala
println(JsonFormatter.format(AsValue.schema(personSchema))
```

Should print something like:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "$ref": "#/definitions/userId"
    },
    "name": {
      "type": "string"
    },
    "required": [
      "id",
      "name"
    ],
    "definitions": {
      "userId": {
        "type": "string"
      }
    }
  }
}
```

**Comment by andyglow** [comment]
hey @gavares 
please find this in `0.5.0`
it won't happen automagically, though
some documentation you can find in here https://github.com/andyglow/scala-jsonschema#free-objects
please also take a look at 
https://github.com/andyglow/scala-jsonschema/blob/8781905646b95b69d4c39b9806d12019b11253ce/modules/play-json/src/test/scala/com/github/andyglow/jsonschema/AsPlaySpec.scala#L70
and https://github.com/andyglow/scala-jsonschema/blob/8781905646b95b69d4c39b9806d12019b11253ce/modules/play-json/src/test/scala/com/github/andyglow/jsonschema/AsPlaySpec.scala#L90 for examples
