### ISSUE TITLE
Is it possible to have json format to scala ?

### ISSUE THREAD

**Issue by ubourdon** [andyglow/scala-jsonschema#73]

**Comment by andyglow** [comment]
hi @ubourdon 
could you explain the idea please?

**Comment by andyglow** [comment]
closing as no context given
please fill free to re-open with more context provided

**Comment by ubourdon** [comment]
Ho sorry. I don't see your message.
It is me that don't understand well the context.
You can forget my issue.

**Comment by andyglow** [comment]
Ok, no problem
