### ISSUE TITLE
base classes

### ISSUE THREAD

**Issue by michellemay** [andyglow/scala-jsonschema#79]
Hi,

I'm wondering should it pick the value `x` inside TBase ?

```
sealed trait TBase { var x: Long = 0 }
case class Derived(var y: String) extends TBase

val jsonSchema = Json.schema[Derived]
println(JsonFormatter.format(AsValue.schema(jsonSchema, json.schema.Version.Draft04())))
```

Gives the result:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "y": {
      "type": "string"
    }
  },
  "required": [
    "y"
  ]
}
```

**Comment by andyglow** [comment]
hello @michellemay 
no it doesn't work this way
fields are inferred from case class in your case

but if it doesn't brake your case you can try
```
sealed trait TBase { def x: Long }
case class Derived(x: Long, y: String) extends TBase
```

**Comment by michellemay** [comment]
This is an interesting solution..  Somewhat uglier when combined with @BeanProperties annotations.

In our case, the base trait is used to define some POJO-like fields like that:
```
trait Base {
  @BeanProperty var requestId: String = ""
}
```

Here, the compiler will generate getter/setter method body placeholder `???`.
We can bypass that by manually implementing get/set methods:

```
trait Base {
  var requestId: String
  def getRequestId = this.requestId
  def setRequestId(x: String) = { this.requestId = x }
}
```

**Comment by andyglow** [comment]
hey. I am wondering does this approach even supported by any json library?
how do you plan to turn the json into the type like this?

**Comment by andyglow** [comment]
may I ask, why do you need to have that field mutable at all?

**Comment by michellemay** [comment]
We have a scala application that implement a java interface contract and will return some objects. These objects are then serialized in json by the java app using an ObjectMapper. This is the reason why it look a bit strange.  In our setup, having vars makes it more convenient in terms of operability.

Indeed, it may sound a bit weird and it probably is..

**Comment by andyglow** [comment]
oh.. I see
if it's java and jackson, why wouldn't you do something like this for jsonschema then?
https://stackoverflow.com/questions/15915971/how-to-generate-json-schema-from-a-jaxb-annotated-class
