### ISSUE TITLE
Json (capital J) is not included with import json._

### ISSUE THREAD

**Issue by iansan5653** [andyglow/scala-jsonschema#81]
I can't figure out how to actually make a schema because the example on the readme seems to be incorrect. `import json._` works to import `json`, which gives me access to the `json.Schema` type as expected. However, I cannot create a schema with `Json.schema` because `Json` is not included in that import at all.

I'm using this version:
```xml
<dependency>
  <groupId>com.github.andyglow</groupId>
  <artifactId>scala-jsonschema_2.11</artifactId>
  <version>0.5.0</version>
</dependency>
```

Is it possible there's some difference in the exports that is not reflected in the documentation?

**Comment by andyglow** [comment]
hello, @iansan5653 
well, there are 2 things that you need
`json.Schema[_]` which is a type representing the json schema of given type
ans `json.Json` which is rather an API. It hosts macro methods used to derive json schemas.

so in case you have no other named `json` in the scope except the json-schema's one, this should work:
```
import json._

case class Foo(id: Int, name: String)

val fooSchema: Schema[Foo] = Json.schema[Foo] // or
val fooSchema: Schema.`object`[Foo] = Json.objectSchema[Foo]
```

in case you absolutely need other packages named `json` (like the play-json one `import play.api.libs.json._`) to be imported, do not import the `json-schema`'s one, just do
```
case class Foo(id: Int, name: String)

val fooSchema: json.Schema[Foo] = json.Json.schema[Foo]
```
or you can always alias package. like
```
import _root_.json. { Schema => JsonSchema, Json => MkJson }
val fooSchema: JsonSchema[Foo] = MkJson.schema[Foo]
```
Hope these recipes helps

**Comment by iansan5653** [comment]
Thanks for the help! It turned out my actual problem was that I was importing `core` instead of the whole thing (even though I typed it right in the original question).
