### ISSUE TITLE
add support for https://github.com/plokhotnyuk/jsoniter-scala

### ISSUE THREAD

**Issue by andyglow** [andyglow/scala-jsonschema#9]

**Comment by andyglow** [comment]
the lib doesn't provide an AST which is a feature, so what would the integration point be?
closing for now. will reopen if come up with something meaningful

**Comment by plokhotnyuk** [comment]
How about using of some custom codec which uses your AST from the core API? 

[Here](https://github.com/jvican/dijon/blob/eeec1112a55657b6ea78912cc785591a7d901061/src/main/scala/com/github/pathikrit/dijon/package.scala#L160-L236) are [here](https://github.com/evolution-gaming/play-json-tools/blob/master/play-json-jsoniter/src/main/scala/com/evolutiongaming/jsonitertool/JsonValueCodecJsValue.scala) are examples of custom codecs for ASTs of Dijon and Play-JSON libraries accordingly.

The best option would be generation of JSON Schema immediately in the jsoniter-scala macro which derives codecs taking in account all possible combination of configuration options that are used for derivation.

**Comment by andyglow** [comment]
hey.. nice idea. i'll think about that
and yes, generating schema directly by the library that derives codec is perfect, it would guarantee that all aspects are aligned. but that is a nice piece of work and I don't think it worth to re-implement it from lib to lib.
But what would definitely help is sort of a standard that would describe how the lib treats different aspects of type/json
like 
```
- option
   how does it treat None
   - absence of the fields
   - fields is there, but null for value
   - empty array (default for ujson)
  how does it treat Some
   - as a value corresponding to the type
   - as an array (default for ujson)
- tuples
   ???
- either
```  
if there are extensions to library, for instance joda-time codecs, how does they work, what to expect

so that would be interesting to specify that stuff so the library/extension author could provide that and on the other side lib like scala-jsonschema would reuse it in order to tailor the schema

what do you think?
