### ISSUE TITLE
can't infer schema for optionable field with default None

### ISSUE THREAD

**Issue by vovateleport** [andyglow/scala-jsonschema#91]
Hi!
```
case class Boo(a: Int)
case class Foo(n: Int, boo: Option[Boo]=None)
Json.schema[Foo].asCirce(Draft07("aaa"))
```
compilation fails with `Can't infer a json value for 'boo'`.

But without `None` compiles OK.
```
case class Boo(a: Int)
case class Foo(n: Int, boo: Option[Boo])
Json.schema[Foo].asCirce(Draft07("aaa"))
```

**Comment by Guillaume-iov42** [comment]
It might be because you didn't provide a Circe encoder for Boo.
It's not None that is the issue. Look at: https://github.com/andyglow/scala-jsonschema/issues/66

**Comment by andyglow** [comment]
Hi all. Although @Guillaume-iov42 pointed right problem I think we can do better. x: Option[T] = None actually forms an exceptional case. Right? So despite the fact at Scala level there is a default, from jsonschema perspective there are still no any default. Which means we don't have to convert None into json which actually only adds confusion. 
I think we can workaround this.

**Comment by Guillaume-iov42** [comment]
Sure, but in case he wants to change the default value at a later time, then he would need the Circe encoder. So I'd argue it's good practice to provide it anyway, when dealing with default values.

**Comment by vovateleport** [comment]
> I had a similar issue.
> It might be because you didn't provide a Circe encoder for `Boo`, so the library doesn't know how to convert `Boo` into Json.
> It's not None that is the issue, it's the default value. Look at: #66

Indeed. Adding codec solved the issue.
Thank you!

**Comment by michellemay** [comment]
Does not work:  https://scastie.scala-lang.org/michellemay/4ZAzMr40TzG5jMd2ZxM8Qg/13

**Comment by andyglow** [comment]
hey, thanks for letting me know
this needs more testing
in 0.6.2 this piece of functionality is going to be slightly refactored
it actually already works somehow on a feature branch. please checkout this https://github.com/andyglow/scala-jsonschema/blob/annotations_definition%2Bdiscrimination/api/src/test/scala/com/github/andyglow/jsonschema/NoneForDefaultValueSpec.scala

**Comment by michellemay** [comment]
Thanks.  I've looked at the branch and I'm not sure I understand everything in there ;)  That said, can I suggest something?  If there exists a chain of ToValue, then use it no matter is the type or value of the object.  

That would boil down to move the resolution of `val toV = c.inferImplicitValue(appliedType(T.toValue, fieldTpe))` and check it's emptyness before resolving the None: `val isNone = if (isOption && toV.isEmpty) {`

**Comment by michellemay** [comment]
Everything in there should work given the proper implicits:

```
  case class Foo1(value: Option[String] = None)
  case class Foo2(noneList: Option[List[String]] = None)
  case class Foo3(someString: Option[String] = Some("abc"))
  case class Foo4(noneListWithComments: Option[List[String]] = None /* weird */)
  case class Foo5(someEmptyList: Option[List[String]] = Some(List.empty[String]))
  case class Foo6(someList: Option[List[String]] = Some(List("abc")))

    println(Json.schema[case2.Foo1]) // OK
    println(Json.schema[case2.Foo2]) // OK
    //println(Json.schema[case2.Foo3]) // scala.reflect.macros.TypecheckException: not found: value Some("abc")
    //println(Json.schema[case2.Foo4]) // scala.reflect.macros.TypecheckException: not found: value None /* weird */
    //println(Json.schema[case2.Foo5]) // scala.reflect.macros.TypecheckException: not found: value Some(List
    //println(Json.schema[case2.Foo6]) // scala.reflect.macros.TypecheckException: not found: value Some(List("abc"))
```

I get error with the /* weird */ comment.  As if the macro gets confused.
I also get errors with all cases of non empty options.

I got all of these cases working with 0.6.0 given a bunch of well crafted implicits. From what I understand, the default values should only be serialized when stringifying the schema.  When inferring the schema, it should not care about them except to determine if the value is required or not.

**Comment by andyglow** [comment]
@michellemay so current logic is such as it looks for ToValue only of the type is `Option` and default value is not `None`.
I am not sure I understand your point regarding using ToValue unconditionally.
Does current solution work for you? it must be in `0.6.3` already.
