### ISSUE TITLE
@discriminator, @discriminatorKey, @definition functionality without using annotations

### ISSUE THREAD

**Issue by coutoPL** [andyglow/scala-jsonschema#99]
**Is your feature request related to a problem? Please describe.**
I'd like to generate json schema from my model, but I don't want to pollute it with annotations from library which won't be used in runtime. I'd like to fully define schema in separate module, based on my model, but without changing it.

**Describe the solution you'd like**
I'd like to use `json.Schema` typeclass and provide implementations which can define the same functionalities which are achievable using `@discriminator`, `@discriminatorKey`, `@definition` annotations.

**Comment by andyglow** [comment]
Hey, @coutoPL 
This kind of functionality is already there.

### Definition
If you need something to be available as definition, wrap the schema into `def`
```
`def`[MyType](id, originalSchema)
```

### Discriminator
For discriminator the api looks like this for now
```
`oneof`[MyType](
  subTypes = Set(
    schema1.duplicate(discriminationKey = "val1"), 
    schema2.duplicate(discriminationKey = "val2")), 
  discriminationField = Some("field"))
```
